blank_issues_enabled: false
contact_links:
  - name: Evalify Community Support
    url: https://github.com/evalify/evalify/issues
    about: Please report your issues here by filling Bug Report form.
